# Generated by Django 2.2.14 on 2023-08-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CCM', 'Construction_Materials'), ('T', 'Tools'), ('Os', 'Others')], max_length=2),
        ),
    ]
