# Generated by Django 2.2.14 on 2023-08-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230801_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CCM', 'ConstructionMaterials'), ('T', 'Tools'), ('Os', 'Others')], max_length=2),
        ),
    ]
