# Generated by Django 2.2.14 on 2023-08-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
    ]
